# Generated by Django 5.0.3 on 2024-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(default='House', max_length=255),
        ),
    ]
